---
title: "CookBook"
author: "Krishna Vaidyanathan"
date: "October 25, 2015"
output: html_document
---

# Getting and Cleaning Data
## Codebook for gathering and tidying data

### Analysis method
 - `dplyr` library is used for data analysis in this assignment
 - Both training and test data sets are respectively collated as data frames
 - They are given accurante column names as read from the the features document
 - Using rbind both train and test data frames are combined
 - The column names are coverted to R friendly names, without sacrificing the information
 - The filtered data with column names that contains the strings "mean" and "std" is created
 - A tidy data is created using a select query
 - Appropriate labels are assigned to the activity_labels by merging with the information provided in `activity_labels.txt`
 - The final filtered data is written to the `run_data_summary.txt` file
 
 ### Variables
 "x"
"subject_id"
"activity_labels"
"tBodyAcc.mean...X"
"tBodyAcc.mean...Y"
"tBodyAcc.mean...Z"
"tGravityAcc.mean...X"
"tGravityAcc.mean...Y"
"tGravityAcc.mean...Z"
"tBodyAccJerk.mean...X"
"tBodyAccJerk.mean...Y"
"tBodyAccJerk.mean...Z"
"tBodyGyro.mean...X"
"tBodyGyro.mean...Y"
"tBodyGyro.mean...Z"
"tBodyGyroJerk.mean...X"
"tBodyGyroJerk.mean...Y"
"tBodyGyroJerk.mean...Z"
"tBodyAccMag.mean.."
"tGravityAccMag.mean.."
"tBodyAccJerkMag.mean.."
"tBodyGyroMag.mean.."
"tBodyGyroJerkMag.mean.."
"fBodyAcc.mean...X"
"fBodyAcc.mean...Y"
"fBodyAcc.mean...Z"
"fBodyAccJerk.mean...X"
"fBodyAccJerk.mean...Y"
"fBodyAccJerk.mean...Z"
"fBodyGyro.mean...X"
"fBodyGyro.mean...Y"
"fBodyGyro.mean...Z"
"fBodyAccMag.mean.."
"fBodyBodyAccJerkMag.mean.."
"fBodyBodyGyroMag.mean.."
"fBodyBodyGyroJerkMag.mean.."
"tBodyAcc.std...X"
"tBodyAcc.std...Y"
"tBodyAcc.std...Z"
"tGravityAcc.std...X"
"tGravityAcc.std...Y"
"tGravityAcc.std...Z"
"tBodyAccJerk.std...X"
"tBodyAccJerk.std...Y"
"tBodyAccJerk.std...Z"
"tBodyGyro.std...X"
"tBodyGyro.std...Y"
"tBodyGyro.std...Z"
"tBodyGyroJerk.std...X"
"tBodyGyroJerk.std...Y"
"tBodyGyroJerk.std...Z"
"tBodyAccMag.std.."
"tGravityAccMag.std.."
"tBodyAccJerkMag.std.."
"tBodyGyroMag.std.."
"tBodyGyroJerkMag.std.."
"fBodyAcc.std...X"
"fBodyAcc.std...Y"
"fBodyAcc.std...Z"
"fBodyAccJerk.std...X"
"fBodyAccJerk.std...Y"
"fBodyAccJerk.std...Z"
"fBodyGyro.std...X"
"fBodyGyro.std...Y"
"fBodyGyro.std...Z"
"fBodyAccMag.std.."
"fBodyBodyAccJerkMag.std.."
"fBodyBodyGyroMag.std.."
"fBodyBodyGyroJerkMag.std.."

 
 ### Additional information
 1. Background information for the data sets can be obtained at http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones